services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["air"]
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: test
      DB_PASSWORD: root
      DB_NAME: gcp_asset_inventory_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: gcp_asset_inventory_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gcp_asset_inventory_db
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5